=====================================
Installation of FreeSurfer7 2024/01/30
=====================================
Version 7.4.1

See download page https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.4.1/

1 download 
  wget https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.4.1/freesurfer-linux-centos8_x86_64-7.4.1.tar.gz

2 install
  mkdir -p /data/opt/apps/freesurfer/7.4.1
  zcat freesurfer-linux-centos8_x86_64-7.4.1.tar.gz | (cd /data/opt/apps/freesurfer/7.4.1; tar xf - --strip-components=1)
  chown -R root:root /data/opt/apps/freesurfer/7.4.1

3 Add license file, otherwise freesurfer errors out
  cp /data/opt/apps/freesurfer/7.1.1/license.txt /data/opt/apps/freesurfer/7.4.1/license.txt

4 Add MCR
  cd  /data/opt/apps/freesurfer/7.4.1/
  ln -s /data/opt/apps/MATLAB/R2023b MCRv97
