=====================================
Installation of FreeSurfer7 01/26/2022
=====================================
Versio 7.2.0

See download page https://surfer.nmr.mgh.harvard.edu/fswiki/rel7downloads

wget https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.2.0/freesurfer-linux-centos7_x86_64-7.2.0.tar.gz
mkdir -p /data/opt/apps/freesurfer/7.2.0
zcat freesurfer-linux-centos7_x86_64-7.2.0.tar.gz | (cd /data/opt/apps/freesurfer/7.2.0; tar xf - --strip-components=1)

# Add license file, otherwise freesurfer errors out
cp /data/opt/apps/freesurfer/7.1.1/license.txt /data/opt/apps/freesurfer/7.2.0/license.txt


=====================================
Installation of FreeSurfer7 9/3/2020
=====================================
Version 7.1.1
Source: https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.1.1/freesurfer-linux-centos8_x86_64-7.1.1.tar.gz

## Steps
wget <Source>
mkdir -p /data/opt/apps/freesurfer/7.1.1
## following takes about 52 minutes to complete
zcat freesurfer-linux-centos7_x86_64-7.1.1.tar.gz | (cd /data/opt/apps/freesurfer/7.1.1/; tar xvf - --strip-components=1

#Freesurfer requires a license obtain from their website
cat << EOF > /data/opt/apps/freesurfer/7.1.1/license.txt
ppapadop@uci.edu
49489
 *CY/c/IAeK0HQ
 FSltCkb2tS1yk
EOF

1. Update 2020-06-15 for 7.1.1
   Per ticket #5590 updated $FREESURFER_HOME/bin/quantifyThalamicNuclei.sh
   Original saved as $FREESURFER_HOME/bin/quantifyThalamicNuclei.sh.bck

2. Update 2020-06-16
   Set execute permissions on the shell script
   chmod +x $FREESURFER_HOME/bin/quantifyThalamicNuclei.sh

=====================================
Installation of FreeSurfer6 9/4/2020
=====================================
Installed Freesurfer 6.0.1
same steps as above 
Source: https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.1/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1.tar.gz
cat << EOF > /data/opt/apps/freesurfer/6.0.1/license.txt
ppapadop@uci.edu
49489
 *CY/c/IAeK0HQ
 FSltCkb2tS1yk
EOF

