=====================================
Installation of FreeSurfer7 9/3/2020
=====================================
Version 7.1.1
Source: https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.1.1/freesurfer-linux-centos8_x86_64-7.1.1.tar.gz

## Steps
wget <Source>
mkdir -p /data/opt/apps/freesurfer/7.1.1
## following takes about 52 minutes to complete
zcat freesurfer-linux-centos7_x86_64-7.1.1.tar.gz | (cd /data/opt/apps/freesurfer/7.1.1/; tar xvf - --strip-components=1

#Freesurfer requires a license obtain from their website
cat << EOF > /data/opt/apps/freesurfer/7.1.1/license.txt
ppapadop@uci.edu
49489
 *CY/c/IAeK0HQ
 FSltCkb2tS1yk
EOF

=====================================
Installation of FreeSurfer6 9/4/2020
=====================================
Installed Freesurfer 6.0.1
same steps as above 
Source: https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.1/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1.tar.gz
cat << EOF > /data/opt/apps/freesurfer/6.0.1/license.txt
ppapadop@uci.edu
49489
 *CY/c/IAeK0HQ
 FSltCkb2tS1yk
EOF

